-- 012_seed_bd_locations — সম্পূর্ণ বিভাগ/জেলা/উপজেলা (codegen, একবার apply)
INSERT INTO divisions (id,name,name_bn) VALUES ('chattagram','Chattagram','চট্টগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('rajshahi','Rajshahi','রাজশাহী') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('khulna','Khulna','খুলনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('barisal','Barisal','বরিশাল') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('sylhet','Sylhet','সিলেট') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('dhaka','Dhaka','ঢাকা') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('rangpur','Rangpur','রংপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO divisions (id,name,name_bn) VALUES ('mymensingh','Mymensingh','ময়মনসিংহ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('comilla','chattagram','Comilla','কুমিল্লা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('feni','chattagram','Feni','ফেনী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('brahmanbaria','chattagram','Brahmanbaria','ব্রাহ্মণবাড়িয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('rangamati','chattagram','Rangamati','রাঙ্গামাটি') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('noakhali','chattagram','Noakhali','নোয়াখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('chandpur','chattagram','Chandpur','চাঁদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('lakshmipur','chattagram','Lakshmipur','লক্ষ্মীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('chattogram','chattagram','Chattogram','চট্টগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('coxsbazar','chattagram','Coxsbazar','কক্সবাজার') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('khagrachhari','chattagram','Khagrachhari','খাগড়াছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('bandarban','chattagram','Bandarban','বান্দরবান') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('sirajganj','rajshahi','Sirajganj','সিরাজগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('pabna','rajshahi','Pabna','পাবনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('bogura','rajshahi','Bogura','বগুড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('rajshahi','rajshahi','Rajshahi','রাজশাহী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('natore','rajshahi','Natore','নাটোর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('joypurhat','rajshahi','Joypurhat','জয়পুরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('chapainawabganj','rajshahi','Chapainawabganj','চাঁপাইনবাবগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('naogaon','rajshahi','Naogaon','নওগাঁ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('jashore','khulna','Jashore','যশোর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('satkhira','khulna','Satkhira','সাতক্ষীরা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('meherpur','khulna','Meherpur','মেহেরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('narail','khulna','Narail','নড়াইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('chuadanga','khulna','Chuadanga','চুয়াডাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('kushtia','khulna','Kushtia','কুষ্টিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('magura','khulna','Magura','মাগুরা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('khulna','khulna','Khulna','খুলনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('bagerhat','khulna','Bagerhat','বাগেরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('jhenaidah','khulna','Jhenaidah','ঝিনাইদহ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('jhalakathi','barisal','Jhalakathi','ঝালকাঠি') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('patuakhali','barisal','Patuakhali','পটুয়াখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('pirojpur','barisal','Pirojpur','পিরোজপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('barisal','barisal','Barisal','বরিশাল') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('bhola','barisal','Bhola','ভোলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('barguna','barisal','Barguna','বরগুনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('sylhet','sylhet','Sylhet','সিলেট') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('moulvibazar','sylhet','Moulvibazar','মৌলভীবাজার') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('habiganj','sylhet','Habiganj','হবিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('sunamganj','sylhet','Sunamganj','সুনামগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('narsingdi','dhaka','Narsingdi','নরসিংদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('gazipur','dhaka','Gazipur','গাজীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('shariatpur','dhaka','Shariatpur','শরীয়তপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('narayanganj','dhaka','Narayanganj','নারায়ণগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('tangail','dhaka','Tangail','টাঙ্গাইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('kishoreganj','dhaka','Kishoreganj','কিশোরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('manikganj','dhaka','Manikganj','মানিকগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('dhaka','dhaka','Dhaka','ঢাকা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('munshiganj','dhaka','Munshiganj','মুন্সিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('rajbari','dhaka','Rajbari','রাজবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('madaripur','dhaka','Madaripur','মাদারীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('gopalganj','dhaka','Gopalganj','গোপালগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('faridpur','dhaka','Faridpur','ফরিদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('panchagarh','rangpur','Panchagarh','পঞ্চগড়') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('dinajpur','rangpur','Dinajpur','দিনাজপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('lalmonirhat','rangpur','Lalmonirhat','লালমনিরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('nilphamari','rangpur','Nilphamari','নীলফামারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('gaibandha','rangpur','Gaibandha','গাইবান্ধা') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('thakurgaon','rangpur','Thakurgaon','ঠাকুরগাঁও') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('rangpur','rangpur','Rangpur','রংপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('kurigram','rangpur','Kurigram','কুড়িগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('sherpur','mymensingh','Sherpur','শেরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('mymensingh','mymensingh','Mymensingh','ময়মনসিংহ') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('jamalpur','mymensingh','Jamalpur','জামালপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO districts (id,division_id,name,name_bn) VALUES ('netrokona','mymensingh','Netrokona','নেত্রকোণা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-debidwar','comilla','Debidwar','দেবিদ্বার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-barura','comilla','Barura','বরুড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-brahmanpara','comilla','Brahmanpara','ব্রাহ্মণপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-chandina','comilla','Chandina','চান্দিনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-chauddagram','comilla','Chauddagram','চৌদ্দগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-daudkandi','comilla','Daudkandi','দাউদকান্দি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-homna','comilla','Homna','হোমনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-laksam','comilla','Laksam','লাকসাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-muradnagar','comilla','Muradnagar','মুরাদনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-nangalkot','comilla','Nangalkot','নাঙ্গলকোট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-comilla-sadar','comilla','Comilla Sadar','কুমিল্লা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-meghna','comilla','Meghna','মেঘনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-monohargonj','comilla','Monohargonj','মনোহরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-sadarsouth','comilla','Sadarsouth','সদর দক্ষিণ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-titas','comilla','Titas','তিতাস') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-burichang','comilla','Burichang','বুড়িচং') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('comilla-lalmai','comilla','Lalmai','লালমাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-chhagalnaiya','feni','Chhagalnaiya','ছাগলনাইয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-feni-sadar','feni','Feni Sadar','ফেনী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-sonagazi','feni','Sonagazi','সোনাগাজী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-fulgazi','feni','Fulgazi','ফুলগাজী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-parshuram','feni','Parshuram','পরশুরাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('feni-daganbhuiyan','feni','Daganbhuiyan','দাগনভূঞা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-brahmanbaria-sadar','brahmanbaria','Brahmanbaria Sadar','ব্রাহ্মণবাড়িয়া সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-kasba','brahmanbaria','Kasba','কসবা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-nasirnagar','brahmanbaria','Nasirnagar','নাসিরনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-sarail','brahmanbaria','Sarail','সরাইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-ashuganj','brahmanbaria','Ashuganj','আশুগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-akhaura','brahmanbaria','Akhaura','আখাউড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-nabinagar','brahmanbaria','Nabinagar','নবীনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-bancharampur','brahmanbaria','Bancharampur','বাঞ্ছারামপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('brahmanbaria-bijoynagar','brahmanbaria','Bijoynagar','বিজয়নগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-rangamati-sadar','rangamati','Rangamati Sadar','রাঙ্গামাটি সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-kaptai','rangamati','Kaptai','কাপ্তাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-kawkhali','rangamati','Kawkhali','কাউখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-baghaichari','rangamati','Baghaichari','বাঘাইছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-barkal','rangamati','Barkal','বরকল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-langadu','rangamati','Langadu','লংগদু') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-rajasthali','rangamati','Rajasthali','রাজস্থলী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-belaichari','rangamati','Belaichari','বিলাইছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-juraichari','rangamati','Juraichari','জুরাছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangamati-naniarchar','rangamati','Naniarchar','নানিয়ারচর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-noakhali-sadar','noakhali','Noakhali Sadar','নোয়াখালী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-companiganj','noakhali','Companiganj','কোম্পানীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-begumganj','noakhali','Begumganj','বেগমগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-hatia','noakhali','Hatia','হাতিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-subarnachar','noakhali','Subarnachar','সুবর্ণচর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-kabirhat','noakhali','Kabirhat','কবিরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-senbug','noakhali','Senbug','সেনবাগ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-chatkhil','noakhali','Chatkhil','চাটখিল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('noakhali-sonaimori','noakhali','Sonaimori','সোনাইমুড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-haimchar','chandpur','Haimchar','হাইমচর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-kachua','chandpur','Kachua','কচুয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-shahrasti','chandpur','Shahrasti','শাহরাস্তি	') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-chandpur-sadar','chandpur','Chandpur Sadar','চাঁদপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-matlab-south','chandpur','Matlab South','মতলব দক্ষিণ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-hajiganj','chandpur','Hajiganj','হাজীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-matlab-north','chandpur','Matlab North','মতলব উত্তর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chandpur-faridgonj','chandpur','Faridgonj','ফরিদগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lakshmipur-lakshmipur-sadar','lakshmipur','Lakshmipur Sadar','লক্ষ্মীপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lakshmipur-kamalnagar','lakshmipur','Kamalnagar','কমলনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lakshmipur-raipur','lakshmipur','Raipur','রায়পুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lakshmipur-ramgati','lakshmipur','Ramgati','রামগতি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lakshmipur-ramganj','lakshmipur','Ramganj','রামগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-rangunia','chattogram','Rangunia','রাঙ্গুনিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-sitakunda','chattogram','Sitakunda','সীতাকুন্ড') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-mirsharai','chattogram','Mirsharai','মীরসরাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-patiya','chattogram','Patiya','পটিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-sandwip','chattogram','Sandwip','সন্দ্বীপ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-banshkhali','chattogram','Banshkhali','বাঁশখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-boalkhali','chattogram','Boalkhali','বোয়ালখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-anwara','chattogram','Anwara','আনোয়ারা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-chandanaish','chattogram','Chandanaish','চন্দনাইশ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-satkania','chattogram','Satkania','সাতকানিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-lohagara','chattogram','Lohagara','লোহাগাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-hathazari','chattogram','Hathazari','হাটহাজারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-fatikchhari','chattogram','Fatikchhari','ফটিকছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-raozan','chattogram','Raozan','রাউজান') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chattogram-karnafuli','chattogram','Karnafuli','কর্ণফুলী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-coxsbazar-sadar','coxsbazar','Coxsbazar Sadar','কক্সবাজার সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-chakaria','coxsbazar','Chakaria','চকরিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-kutubdia','coxsbazar','Kutubdia','কুতুবদিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-ukhiya','coxsbazar','Ukhiya','উখিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-moheshkhali','coxsbazar','Moheshkhali','মহেশখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-pekua','coxsbazar','Pekua','পেকুয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-ramu','coxsbazar','Ramu','রামু') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-teknaf','coxsbazar','Teknaf','টেকনাফ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('coxsbazar-eidgaon','coxsbazar','Eidgaon','ঈদগাঁও') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-khagrachhari-sadar','khagrachhari','Khagrachhari Sadar','খাগড়াছড়ি সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-dighinala','khagrachhari','Dighinala','দিঘীনালা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-panchari','khagrachhari','Panchari','পানছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-laxmichhari','khagrachhari','Laxmichhari','লক্ষীছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-mohalchari','khagrachhari','Mohalchari','মহালছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-manikchari','khagrachhari','Manikchari','মানিকছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-ramgarh','khagrachhari','Ramgarh','রামগড়') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-matiranga','khagrachhari','Matiranga','মাটিরাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khagrachhari-guimara','khagrachhari','Guimara','গুইমারা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-bandarban-sadar','bandarban','Bandarban Sadar','বান্দরবান সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-alikadam','bandarban','Alikadam','আলীকদম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-naikhongchhari','bandarban','Naikhongchhari','নাইক্ষ্যংছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-rowangchhari','bandarban','Rowangchhari','রোয়াংছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-lama','bandarban','Lama','লামা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-ruma','bandarban','Ruma','রুমা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bandarban-thanchi','bandarban','Thanchi','থানচি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-belkuchi','sirajganj','Belkuchi','বেলকুচি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-chauhali','sirajganj','Chauhali','চৌহালি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-kamarkhand','sirajganj','Kamarkhand','কামারখন্দ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-kazipur','sirajganj','Kazipur','কাজীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-raigonj','sirajganj','Raigonj','রায়গঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-shahjadpur','sirajganj','Shahjadpur','শাহজাদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-sirajganj-sadar','sirajganj','Sirajganj Sadar','সিরাজগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-tarash','sirajganj','Tarash','তাড়াশ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sirajganj-ullapara','sirajganj','Ullapara','উল্লাপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-sujanagar','pabna','Sujanagar','সুজানগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-ishurdi','pabna','Ishurdi','ঈশ্বরদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-bhangura','pabna','Bhangura','ভাঙ্গুড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-pabna-sadar','pabna','Pabna Sadar','পাবনা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-bera','pabna','Bera','বেড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-atghoria','pabna','Atghoria','আটঘরিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-chatmohar','pabna','Chatmohar','চাটমোহর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-santhia','pabna','Santhia','সাঁথিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pabna-faridpur','pabna','Faridpur','ফরিদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-kahaloo','bogura','Kahaloo','কাহালু') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-bogra-sadar','bogura','Bogra Sadar','বগুড়া সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-shariakandi','bogura','Shariakandi','সারিয়াকান্দি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-shajahanpur','bogura','Shajahanpur','শাজাহানপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-dupchanchia','bogura','Dupchanchia','দুপচাচিঁয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-adamdighi','bogura','Adamdighi','আদমদিঘি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-nondigram','bogura','Nondigram','নন্দিগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-sonatala','bogura','Sonatala','সোনাতলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-dhunot','bogura','Dhunot','ধুনট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-gabtali','bogura','Gabtali','গাবতলী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-sherpur','bogura','Sherpur','শেরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bogura-shibganj','bogura','Shibganj','শিবগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-paba','rajshahi','Paba','পবা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-durgapur','rajshahi','Durgapur','দুর্গাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-mohonpur','rajshahi','Mohonpur','মোহনপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-charghat','rajshahi','Charghat','চারঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-puthia','rajshahi','Puthia','পুঠিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-bagha','rajshahi','Bagha','বাঘা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-godagari','rajshahi','Godagari','গোদাগাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-tanore','rajshahi','Tanore','তানোর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajshahi-bagmara','rajshahi','Bagmara','বাগমারা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-natore-sadar','natore','Natore Sadar','নাটোর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-singra','natore','Singra','সিংড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-baraigram','natore','Baraigram','বড়াইগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-bagatipara','natore','Bagatipara','বাগাতিপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-lalpur','natore','Lalpur','লালপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-gurudaspur','natore','Gurudaspur','গুরুদাসপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('natore-naldanga','natore','Naldanga','নলডাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('joypurhat-akkelpur','joypurhat','Akkelpur','আক্কেলপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('joypurhat-kalai','joypurhat','Kalai','কালাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('joypurhat-khetlal','joypurhat','Khetlal','ক্ষেতলাল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('joypurhat-panchbibi','joypurhat','Panchbibi','পাঁচবিবি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('joypurhat-joypurhat-sadar','joypurhat','Joypurhat Sadar','জয়পুরহাট সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chapainawabganj-chapainawabganj-sadar','chapainawabganj','Chapainawabganj Sadar','চাঁপাইনবাবগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chapainawabganj-gomostapur','chapainawabganj','Gomostapur','গোমস্তাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chapainawabganj-nachol','chapainawabganj','Nachol','নাচোল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chapainawabganj-bholahat','chapainawabganj','Bholahat','ভোলাহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chapainawabganj-shibganj','chapainawabganj','Shibganj','শিবগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-mohadevpur','naogaon','Mohadevpur','মহাদেবপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-badalgachi','naogaon','Badalgachi','বদলগাছী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-patnitala','naogaon','Patnitala','পত্নিতলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-dhamoirhat','naogaon','Dhamoirhat','ধামইরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-niamatpur','naogaon','Niamatpur','নিয়ামতপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-manda','naogaon','Manda','মান্দা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-atrai','naogaon','Atrai','আত্রাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-raninagar','naogaon','Raninagar','রাণীনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-naogaon-sadar','naogaon','Naogaon Sadar','নওগাঁ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-porsha','naogaon','Porsha','পোরশা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('naogaon-sapahar','naogaon','Sapahar','সাপাহার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-manirampur','jashore','Manirampur','মণিরামপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-abhaynagar','jashore','Abhaynagar','অভয়নগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-bagherpara','jashore','Bagherpara','বাঘারপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-chougachha','jashore','Chougachha','চৌগাছা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-jhikargacha','jashore','Jhikargacha','ঝিকরগাছা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-keshabpur','jashore','Keshabpur','কেশবপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-jessore-sadar','jashore','Jessore Sadar','যশোর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jashore-sharsha','jashore','Sharsha','শার্শা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-assasuni','satkhira','Assasuni','আশাশুনি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-debhata','satkhira','Debhata','দেবহাটা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-kalaroa','satkhira','Kalaroa','কলারোয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-satkhira-sadar','satkhira','Satkhira Sadar','সাতক্ষীরা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-shyamnagar','satkhira','Shyamnagar','শ্যামনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-tala','satkhira','Tala','তালা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('satkhira-kaliganj','satkhira','Kaliganj','কালিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('meherpur-mujibnagar','meherpur','Mujibnagar','মুজিবনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('meherpur-meherpur-sadar','meherpur','Meherpur Sadar','মেহেরপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('meherpur-gangni','meherpur','Gangni','গাংনী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narail-narail-sadar','narail','Narail Sadar','নড়াইল সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narail-lohagara','narail','Lohagara','লোহাগড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narail-kalia','narail','Kalia','কালিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chuadanga-chuadanga-sadar','chuadanga','Chuadanga Sadar','চুয়াডাঙ্গা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chuadanga-alamdanga','chuadanga','Alamdanga','আলমডাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chuadanga-damurhuda','chuadanga','Damurhuda','দামুড়হুদা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('chuadanga-jibannagar','chuadanga','Jibannagar','জীবননগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-kushtia-sadar','kushtia','Kushtia Sadar','কুষ্টিয়া সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-kumarkhali','kushtia','Kumarkhali','কুমারখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-khoksa','kushtia','Khoksa','খোকসা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-mirpur','kushtia','Mirpur','মিরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-daulatpur','kushtia','Daulatpur','দৌলতপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kushtia-bheramara','kushtia','Bheramara','ভেড়ামারা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('magura-shalikha','magura','Shalikha','শালিখা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('magura-sreepur','magura','Sreepur','শ্রীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('magura-magura-sadar','magura','Magura Sadar','মাগুরা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('magura-mohammadpur','magura','Mohammadpur','মহম্মদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-paikgasa','khulna','Paikgasa','পাইকগাছা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-fultola','khulna','Fultola','ফুলতলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-digholia','khulna','Digholia','দিঘলিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-rupsha','khulna','Rupsha','রূপসা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-terokhada','khulna','Terokhada','তেরখাদা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-dumuria','khulna','Dumuria','ডুমুরিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-botiaghata','khulna','Botiaghata','বটিয়াঘাটা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-dakop','khulna','Dakop','দাকোপ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('khulna-koyra','khulna','Koyra','কয়রা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-fakirhat','bagerhat','Fakirhat','ফকিরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-bagerhat-sadar','bagerhat','Bagerhat Sadar','বাগেরহাট সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-mollahat','bagerhat','Mollahat','মোল্লাহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-sarankhola','bagerhat','Sarankhola','শরণখোলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-rampal','bagerhat','Rampal','রামপাল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-morrelganj','bagerhat','Morrelganj','মোড়েলগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-kachua','bagerhat','Kachua','কচুয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-mongla','bagerhat','Mongla','মোংলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bagerhat-chitalmari','bagerhat','Chitalmari','চিতলমারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-jhenaidah-sadar','jhenaidah','Jhenaidah Sadar','ঝিনাইদহ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-shailkupa','jhenaidah','Shailkupa','শৈলকুপা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-harinakundu','jhenaidah','Harinakundu','হরিণাকুন্ডু') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-kaliganj','jhenaidah','Kaliganj','কালীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-kotchandpur','jhenaidah','Kotchandpur','কোটচাঁদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhenaidah-moheshpur','jhenaidah','Moheshpur','মহেশপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhalakathi-jhalakathi-sadar','jhalakathi','Jhalakathi Sadar','ঝালকাঠি সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhalakathi-kathalia','jhalakathi','Kathalia','কাঠালিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhalakathi-nalchity','jhalakathi','Nalchity','নলছিটি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jhalakathi-rajapur','jhalakathi','Rajapur','রাজাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-bauphal','patuakhali','Bauphal','বাউফল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-patuakhali-sadar','patuakhali','Patuakhali Sadar','পটুয়াখালী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-dumki','patuakhali','Dumki','দুমকি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-dashmina','patuakhali','Dashmina','দশমিনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-kalapara','patuakhali','Kalapara','কলাপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-mirzaganj','patuakhali','Mirzaganj','মির্জাগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-galachipa','patuakhali','Galachipa','গলাচিপা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('patuakhali-rangabali','patuakhali','Rangabali','রাঙ্গাবালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-pirojpur-sadar','pirojpur','Pirojpur Sadar','পিরোজপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-nazirpur','pirojpur','Nazirpur','নাজিরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-kawkhali','pirojpur','Kawkhali','কাউখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-indurkani','pirojpur','Indurkani','ইন্দুরকানী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-bhandaria','pirojpur','Bhandaria','ভান্ডারিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-mathbaria','pirojpur','Mathbaria','মঠবাড়ীয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('pirojpur-nesarabad','pirojpur','Nesarabad','নেছারাবাদ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-barisal-sadar','barisal','Barisal Sadar','বরিশাল সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-bakerganj','barisal','Bakerganj','বাকেরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-babuganj','barisal','Babuganj','বাবুগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-wazirpur','barisal','Wazirpur','উজিরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-banaripara','barisal','Banaripara','বানারীপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-gournadi','barisal','Gournadi','গৌরনদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-agailjhara','barisal','Agailjhara','আগৈলঝাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-mehendiganj','barisal','Mehendiganj','মেহেন্দিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-muladi','barisal','Muladi','মুলাদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barisal-hizla','barisal','Hizla','হিজলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-bhola-sadar','bhola','Bhola Sadar','ভোলা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-borhanuddin','bhola','Borhanuddin','বোরহানউদ্দিন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-charfesson','bhola','Charfesson','চরফ্যাশন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-doulatkhan','bhola','Doulatkhan','দৌলতখান') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-monpura','bhola','Monpura','মনপুরা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-tazumuddin','bhola','Tazumuddin','তজুমদ্দিন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('bhola-lalmohan','bhola','Lalmohan','লালমোহন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-amtali','barguna','Amtali','আমতলী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-barguna-sadar','barguna','Barguna Sadar','বরগুনা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-betagi','barguna','Betagi','বেতাগী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-bamna','barguna','Bamna','বামনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-pathorghata','barguna','Pathorghata','পাথরঘাটা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('barguna-taltali','barguna','Taltali','তালতলি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-balaganj','sylhet','Balaganj','বালাগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-beanibazar','sylhet','Beanibazar','বিয়ানীবাজার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-bishwanath','sylhet','Bishwanath','বিশ্বনাথ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-companiganj','sylhet','Companiganj','কোম্পানীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-fenchuganj','sylhet','Fenchuganj','ফেঞ্চুগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-golapganj','sylhet','Golapganj','গোলাপগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-gowainghat','sylhet','Gowainghat','গোয়াইনঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-jaintiapur','sylhet','Jaintiapur','জৈন্তাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-kanaighat','sylhet','Kanaighat','কানাইঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-sylhet-sadar','sylhet','Sylhet Sadar','সিলেট সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-zakiganj','sylhet','Zakiganj','জকিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-dakshinsurma','sylhet','Dakshinsurma','দক্ষিণ সুরমা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sylhet-osmaninagar','sylhet','Osmaninagar','ওসমানী নগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-barlekha','moulvibazar','Barlekha','বড়লেখা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-kamolganj','moulvibazar','Kamolganj','কমলগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-kulaura','moulvibazar','Kulaura','কুলাউড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-moulvibazar-sadar','moulvibazar','Moulvibazar Sadar','মৌলভীবাজার সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-rajnagar','moulvibazar','Rajnagar','রাজনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-sreemangal','moulvibazar','Sreemangal','শ্রীমঙ্গল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('moulvibazar-juri','moulvibazar','Juri','জুড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-nabiganj','habiganj','Nabiganj','নবীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-bahubal','habiganj','Bahubal','বাহুবল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-ajmiriganj','habiganj','Ajmiriganj','আজমিরীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-baniachong','habiganj','Baniachong','বানিয়াচং') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-lakhai','habiganj','Lakhai','লাখাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-chunarughat','habiganj','Chunarughat','চুনারুঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-habiganj-sadar','habiganj','Habiganj Sadar','হবিগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-madhabpur','habiganj','Madhabpur','মাধবপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('habiganj-shaistaganj','habiganj','Shaistaganj','শায়েস্তাগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-sunamganj-sadar','sunamganj','Sunamganj Sadar','সুনামগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-shantiganj','sunamganj','Shantiganj','শান্তিগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-bishwambarpur','sunamganj','Bishwambarpur','বিশ্বম্ভরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-chhatak','sunamganj','Chhatak','ছাতক') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-jagannathpur','sunamganj','Jagannathpur','জগন্নাথপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-dowarabazar','sunamganj','Dowarabazar','দোয়ারাবাজার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-tahirpur','sunamganj','Tahirpur','তাহিরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-dharmapasha','sunamganj','Dharmapasha','ধর্মপাশা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-jamalganj','sunamganj','Jamalganj','জামালগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-shalla','sunamganj','Shalla','শাল্লা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-derai','sunamganj','Derai','দিরাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sunamganj-madhyanagar','sunamganj','Madhyanagar','মধ্যনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-belabo','narsingdi','Belabo','বেলাবো') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-monohardi','narsingdi','Monohardi','মনোহরদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-narsingdi-sadar','narsingdi','Narsingdi Sadar','নরসিংদী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-palash','narsingdi','Palash','পলাশ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-raipura','narsingdi','Raipura','রায়পুরা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narsingdi-shibpur','narsingdi','Shibpur','শিবপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gazipur-kaliganj','gazipur','Kaliganj','কালীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gazipur-kaliakair','gazipur','Kaliakair','কালিয়াকৈর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gazipur-kapasia','gazipur','Kapasia','কাপাসিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gazipur-gazipur-sadar','gazipur','Gazipur Sadar','গাজীপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gazipur-sreepur','gazipur','Sreepur','শ্রীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-shariatpur-sadar','shariatpur','Shariatpur Sadar','শরিয়তপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-naria','shariatpur','Naria','নড়িয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-zajira','shariatpur','Zajira','জাজিরা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-gosairhat','shariatpur','Gosairhat','গোসাইরহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-bhedarganj','shariatpur','Bhedarganj','ভেদরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('shariatpur-damudya','shariatpur','Damudya','ডামুড্যা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narayanganj-araihazar','narayanganj','Araihazar','আড়াইহাজার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narayanganj-bandar','narayanganj','Bandar','বন্দর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narayanganj-narayanganj-sadar','narayanganj','Narayanganj Sadar','নারায়নগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narayanganj-rupganj','narayanganj','Rupganj','রূপগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('narayanganj-sonargaon','narayanganj','Sonargaon','সোনারগাঁ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-basail','tangail','Basail','বাসাইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-bhuapur','tangail','Bhuapur','ভুয়াপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-delduar','tangail','Delduar','দেলদুয়ার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-ghatail','tangail','Ghatail','ঘাটাইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-gopalpur','tangail','Gopalpur','গোপালপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-madhupur','tangail','Madhupur','মধুপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-mirzapur','tangail','Mirzapur','মির্জাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-nagarpur','tangail','Nagarpur','নাগরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-sakhipur','tangail','Sakhipur','সখিপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-tangail-sadar','tangail','Tangail Sadar','টাঙ্গাইল সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-kalihati','tangail','Kalihati','কালিহাতী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('tangail-dhanbari','tangail','Dhanbari','ধনবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-itna','kishoreganj','Itna','ইটনা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-katiadi','kishoreganj','Katiadi','কটিয়াদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-bhairab','kishoreganj','Bhairab','ভৈরব') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-tarail','kishoreganj','Tarail','তাড়াইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-hossainpur','kishoreganj','Hossainpur','হোসেনপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-pakundia','kishoreganj','Pakundia','পাকুন্দিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-kuliarchar','kishoreganj','Kuliarchar','কুলিয়ারচর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-kishoreganj-sadar','kishoreganj','Kishoreganj Sadar','কিশোরগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-karimgonj','kishoreganj','Karimgonj','করিমগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-bajitpur','kishoreganj','Bajitpur','বাজিতপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-austagram','kishoreganj','Austagram','অষ্টগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-mithamoin','kishoreganj','Mithamoin','মিঠামইন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kishoreganj-nikli','kishoreganj','Nikli','নিকলী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-harirampur','manikganj','Harirampur','হরিরামপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-saturia','manikganj','Saturia','সাটুরিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-manikganj-sadar','manikganj','Manikganj Sadar','মানিকগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-gior','manikganj','Gior','ঘিওর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-shibaloy','manikganj','Shibaloy','শিবালয়') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-doulatpur','manikganj','Doulatpur','দৌলতপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('manikganj-singiar','manikganj','Singiar','সিংগাইর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dhaka-savar','dhaka','Savar','সাভার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dhaka-dhamrai','dhaka','Dhamrai','ধামরাই') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dhaka-keraniganj','dhaka','Keraniganj','কেরাণীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dhaka-nawabganj','dhaka','Nawabganj','নবাবগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dhaka-dohar','dhaka','Dohar','দোহার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-munshiganj-sadar','munshiganj','Munshiganj Sadar','মুন্সিগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-sreenagar','munshiganj','Sreenagar','শ্রীনগর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-sirajdikhan','munshiganj','Sirajdikhan','সিরাজদিখান') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-louhajanj','munshiganj','Louhajanj','লৌহজং') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-gajaria','munshiganj','Gajaria','গজারিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('munshiganj-tongibari','munshiganj','Tongibari','টংগীবাড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajbari-rajbari-sadar','rajbari','Rajbari Sadar','রাজবাড়ী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajbari-goalanda','rajbari','Goalanda','গোয়ালন্দ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajbari-pangsa','rajbari','Pangsa','পাংশা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajbari-baliakandi','rajbari','Baliakandi','বালিয়াকান্দি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rajbari-kalukhali','rajbari','Kalukhali','কালুখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('madaripur-madaripur-sadar','madaripur','Madaripur Sadar','মাদারীপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('madaripur-shibchar','madaripur','Shibchar','শিবচর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('madaripur-kalkini','madaripur','Kalkini','কালকিনি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('madaripur-rajoir','madaripur','Rajoir','রাজৈর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('madaripur-dasar','madaripur','Dasar','ডাসার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gopalganj-gopalganj-sadar','gopalganj','Gopalganj Sadar','গোপালগঞ্জ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gopalganj-kashiani','gopalganj','Kashiani','কাশিয়ানী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gopalganj-tungipara','gopalganj','Tungipara','টুংগীপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gopalganj-kotalipara','gopalganj','Kotalipara','কোটালীপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gopalganj-muksudpur','gopalganj','Muksudpur','মুকসুদপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-faridpur-sadar','faridpur','Faridpur Sadar','ফরিদপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-alfadanga','faridpur','Alfadanga','আলফাডাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-boalmari','faridpur','Boalmari','বোয়ালমারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-sadarpur','faridpur','Sadarpur','সদরপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-nagarkanda','faridpur','Nagarkanda','নগরকান্দা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-bhanga','faridpur','Bhanga','ভাঙ্গা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-charbhadrasan','faridpur','Charbhadrasan','চরভদ্রাসন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-madhukhali','faridpur','Madhukhali','মধুখালী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('faridpur-saltha','faridpur','Saltha','সালথা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('panchagarh-panchagarh-sadar','panchagarh','Panchagarh Sadar','পঞ্চগড় সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('panchagarh-debiganj','panchagarh','Debiganj','দেবীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('panchagarh-boda','panchagarh','Boda','বোদা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('panchagarh-atwari','panchagarh','Atwari','আটোয়ারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('panchagarh-tetulia','panchagarh','Tetulia','তেতুলিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-nawabganj','dinajpur','Nawabganj','নবাবগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-birganj','dinajpur','Birganj','বীরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-ghoraghat','dinajpur','Ghoraghat','ঘোড়াঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-birampur','dinajpur','Birampur','বিরামপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-parbatipur','dinajpur','Parbatipur','পার্বতীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-bochaganj','dinajpur','Bochaganj','বোচাগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-kaharol','dinajpur','Kaharol','কাহারোল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-fulbari','dinajpur','Fulbari','ফুলবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-dinajpur-sadar','dinajpur','Dinajpur Sadar','দিনাজপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-hakimpur','dinajpur','Hakimpur','হাকিমপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-khansama','dinajpur','Khansama','খানসামা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-birol','dinajpur','Birol','বিরল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('dinajpur-chirirbandar','dinajpur','Chirirbandar','চিরিরবন্দর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lalmonirhat-lalmonirhat-sadar','lalmonirhat','Lalmonirhat Sadar','লালমনিরহাট সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lalmonirhat-kaliganj','lalmonirhat','Kaliganj','কালীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lalmonirhat-hatibandha','lalmonirhat','Hatibandha','হাতীবান্ধা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lalmonirhat-patgram','lalmonirhat','Patgram','পাটগ্রাম') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('lalmonirhat-aditmari','lalmonirhat','Aditmari','আদিতমারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-syedpur','nilphamari','Syedpur','সৈয়দপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-domar','nilphamari','Domar','ডোমার') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-dimla','nilphamari','Dimla','ডিমলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-jaldhaka','nilphamari','Jaldhaka','জলঢাকা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-kishorganj','nilphamari','Kishorganj','কিশোরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('nilphamari-nilphamari-sadar','nilphamari','Nilphamari Sadar','নীলফামারী সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-sadullapur','gaibandha','Sadullapur','সাদুল্লাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-gaibandha-sadar','gaibandha','Gaibandha Sadar','গাইবান্ধা সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-palashbari','gaibandha','Palashbari','পলাশবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-saghata','gaibandha','Saghata','সাঘাটা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-gobindaganj','gaibandha','Gobindaganj','গোবিন্দগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-sundarganj','gaibandha','Sundarganj','সুন্দরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('gaibandha-phulchari','gaibandha','Phulchari','ফুলছড়ি') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('thakurgaon-thakurgaon-sadar','thakurgaon','Thakurgaon Sadar','ঠাকুরগাঁও সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('thakurgaon-pirganj','thakurgaon','Pirganj','পীরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('thakurgaon-ranisankail','thakurgaon','Ranisankail','রাণীশংকৈল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('thakurgaon-haripur','thakurgaon','Haripur','হরিপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('thakurgaon-baliadangi','thakurgaon','Baliadangi','বালিয়াডাঙ্গী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-rangpur-sadar','rangpur','Rangpur Sadar','রংপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-gangachara','rangpur','Gangachara','গংগাচড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-taragonj','rangpur','Taragonj','তারাগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-badargonj','rangpur','Badargonj','বদরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-mithapukur','rangpur','Mithapukur','মিঠাপুকুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-pirgonj','rangpur','Pirgonj','পীরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-kaunia','rangpur','Kaunia','কাউনিয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('rangpur-pirgacha','rangpur','Pirgacha','পীরগাছা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-kurigram-sadar','kurigram','Kurigram Sadar','কুড়িগ্রাম সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-nageshwari','kurigram','Nageshwari','নাগেশ্বরী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-bhurungamari','kurigram','Bhurungamari','ভুরুঙ্গামারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-phulbari','kurigram','Phulbari','ফুলবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-rajarhat','kurigram','Rajarhat','রাজারহাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-ulipur','kurigram','Ulipur','উলিপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-chilmari','kurigram','Chilmari','চিলমারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-rowmari','kurigram','Rowmari','রৌমারী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('kurigram-charrajibpur','kurigram','Charrajibpur','চর রাজিবপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sherpur-sherpur-sadar','sherpur','Sherpur Sadar','শেরপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sherpur-nalitabari','sherpur','Nalitabari','নালিতাবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sherpur-sreebordi','sherpur','Sreebordi','শ্রীবরদী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sherpur-nokla','sherpur','Nokla','নকলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('sherpur-jhenaigati','sherpur','Jhenaigati','ঝিনাইগাতী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-fulbaria','mymensingh','Fulbaria','ফুলবাড়ীয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-trishal','mymensingh','Trishal','ত্রিশাল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-bhaluka','mymensingh','Bhaluka','ভালুকা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-muktagacha','mymensingh','Muktagacha','মুক্তাগাছা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-mymensingh-sadar','mymensingh','Mymensingh Sadar','ময়মনসিংহ সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-dhobaura','mymensingh','Dhobaura','ধোবাউড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-phulpur','mymensingh','Phulpur','ফুলপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-haluaghat','mymensingh','Haluaghat','হালুয়াঘাট') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-gouripur','mymensingh','Gouripur','গৌরীপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-gafargaon','mymensingh','Gafargaon','গফরগাঁও') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-iswarganj','mymensingh','Iswarganj','ঈশ্বরগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-nandail','mymensingh','Nandail','নান্দাইল') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('mymensingh-tarakanda','mymensingh','Tarakanda','তারাকান্দা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-jamalpur-sadar','jamalpur','Jamalpur Sadar','জামালপুর সদর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-melandah','jamalpur','Melandah','মেলান্দহ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-islampur','jamalpur','Islampur','ইসলামপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-dewangonj','jamalpur','Dewangonj','দেওয়ানগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-sarishabari','jamalpur','Sarishabari','সরিষাবাড়ী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-madarganj','jamalpur','Madarganj','মাদারগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('jamalpur-bokshiganj','jamalpur','Bokshiganj','বকশীগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-barhatta','netrokona','Barhatta','বারহাট্টা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-durgapur','netrokona','Durgapur','দুর্গাপুর') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-kendua','netrokona','Kendua','কেন্দুয়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-atpara','netrokona','Atpara','আটপাড়া') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-madan','netrokona','Madan','মদন') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-khaliajuri','netrokona','Khaliajuri','খালিয়াজুরী') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-kalmakanda','netrokona','Kalmakanda','কলমাকান্দা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-mohongonj','netrokona','Mohongonj','মোহনগঞ্জ') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-purbadhala','netrokona','Purbadhala','পূর্বধলা') ON CONFLICT (id) DO NOTHING;
INSERT INTO upazilas (id,district_id,name,name_bn) VALUES ('netrokona-netrokona-sadar','netrokona','Netrokona Sadar','নেত্রকোণা সদর') ON CONFLICT (id) DO NOTHING;
